# Where things are
source:       .
destination:  ./_site
plugins:      ./_plugins
layouts:      ./_layouts
paginate:     8

# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
textile_ext:  "textile"

# Filtering Content
show_drafts:  null
limit_posts:  150
future:       true
unpublished:  false
truncate: 150

# Conversion
markdown:     rdiscount
highlighter:  pygments
lsi:          false
excerpt_separator: "\n\n"

# Serving
detach:       false
port:         4000
host:         127.0.0.1
baseurl:      "" # does not include hostname

# Outputting
permalink:     /:year/:month/:day/:title
paginate_path: /page:num
timezone:      null

#站点基础配置
title: SafeLong
subTitle: 记录工作生活的点点滴滴.
description: safelong的大杂烩！它是基于 Jekyll 搭建起来的。在这里是用来快速记录工作，学习，生活的一点一滴的地方。
url: 
feed: /atom.xml
siteTitle: SafeLong的大杂烩

#菜单配置
nav:
  - text: 首页
    url: /
    icon: icon-home
    class: home
  - text: 文章分类
    url: /archives.html
    icon: icon-reorder
    class: none
  - text: 关于我
    url: /about/index.html
    icon: icon-user
    class: none
  - text: 留言板
    url: /guestbook.html
    icon: icon-heart
    class: none
  - text: 博客源代码
    url: https://github.com/safelong
    icon: icon-github
    class: none

page:
  - text: 文章分类
    url: /archives.html
    last: true
  - text: 友情链接
    url: /links.html
    last: true
  - text: 关于我
    url: /about/index.html
    last: false

author:
  name: safelong

#个人信息
about: "<p>挨踢攻城狮一头，目前从事web项目的开发管理。</p>     
<p>7年工作经验，没有换过公司。</p>
<p>管理的同时，也兼顾开发。</p>
<p>喜欢打篮球，喜欢研究国产手机。</p>
<p>不喜欢玩游戏，偶尔打打牌。</p>
<p>性格随性，思维理性。</p>"
url: http://www.safelong.cc
qq: 37127882
email: lzc2125@163.com
duoshuo: safelong
#beian: 浙ICP备12026616号
#cnzz: 119959
weibo: 1040804112
github: safelong

# 404.html
404_heading: '对不起，无法找到该页。'
404_content: '页面将在数秒内自动跳转回 <a href="http://safelong.github.io">safelong.cc</a>'