markdown: rdiscount
permalink: /:title/
url: 
name: 89Ao.info
author: safelong
qq: 37127882
email: lzc2125@163.com
duoshuo: 89ao
#beian: 浙ICP备12026616号
#cnzz: 119959
weibo: 2067815867
github: safelong
pygments: true
safe: true
paginate: 20
about: "攻城狮一头，目前从事web项目的开发。     
5年开发经验，2年管理经验。
管理的同时，也兼顾开发。
喜欢打篮球，喜欢研究国产手机。
不喜欢玩游戏，偶尔打打牌。"
